language: node_js
node_js:
  - 0.12
  - 4
  - 6
env:
  - PROJECT_NAME=capture
  - PROJECT_NAME=persist
  - PROJECT_NAME=retrieve
  - PROJECT_NAME=replay
  - PROJECT_NAME=shared
git:
  depth: 1
script: cd $PROJECT_NAME && npm install && npm test
